# Generated by Django 5.0.1 on 2024-01-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='texto')),
                ('emotion_label', models.CharField(choices=[('joy', 'Joy'), ('fear', 'Fear'), ('sadness', 'Sadness'), ('surprise', 'Surprise'), ('disgust', 'Disgust'), ('anger', 'Anger'), ('others', 'Others'), ('error', 'Error')], max_length=10, verbose_name='etiqueta de emocion')),
                ('sentiment_label', models.CharField(choices=[('POS', 'Pos'), ('NEG', 'Neg'), ('NEU', 'Neu'), ('ERROR', 'Error')], max_length=5, verbose_name='etiqueta sentimiento')),
            ],
        ),
    ]
