# Generated by Django 5.0.1 on 2024-01-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huggingface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='texto'),
        ),
    ]
